# We pretend to be erlang because we can't use the python support in travis-ci
# see also: https://groups.google.com/forum/#!msg/travis-ci/uJgu35XKdmI/CctnUkYnEJEJ
language: erlang
before_install:
  - lsb_release -a  # get info on the operating system
  - sudo apt-get install -qq gfortran python python-dev python-setuptools python-numpy python-lxml # install dependencies
  - DEPTH=300; while [ "$(git describe 2> /dev/null)" == "" ]; do DEPTH=$(($DEPTH+200)); git fetch origin --depth=$DEPTH --quiet; done  # continue fetching more older commits until git describe is able to reach the last tagged version
  - easy_install SQLAlchemy
  - easy_install Cheetah
  - easy_install pycrypto
  - easy_install Twisted
  - easy_install pyparsing
  - easy_install pyasn1
  - easy_install obspy.core
install:
  - sudo python setup.py -q install
script:
  - sudo python seishub/core/test.py
notifications:
    email: false
