language: python
python:
  - "2.7"
sudo: false
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"  
  - hash -r
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a
  - conda config --add channels obspy
  - conda install "obspy<1.1" "twisted<16" "zope.interface<4.1" cheetah "sqlalchemy<0.8" pyopenssl lxml pycrypto pyasn1 pyparsing
install:
  - pip install --no-deps .
script:
  - mkdir empty; cd empty
  - seishub-runtests
notifications:
    email: false
